spring:
  application:
    name: skyway
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:skyway_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
        order_updates: true
app:
  jwt:
    secret: ${secret_key}
    expiration: 86400000

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: "/"
